# Generated by Django 2.0.5 on 2018-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(default='', max_length=100)),
                ('exclusion_types', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
